### ISSUE TITLE
Нормализация данных

### ISSUE THREAD

**Issue by jamm1985** [jamm1985/seismo-ml-phase-picker#7]
Мы будем использовать [датасэт сейсмологической лаборатории Калифорнийского университета](https://scedc.caltech.edu/research-tools/deeplearning.html#picking_polarity). 

Набор данных `scsn_ps_2000_2017_shuf.hdf5` содержит `4773750` примеров P, S вступлений и сейсмического шума. Каждый по 3 компоненты, 4 сек, 100 Гц (400 значений на канал).

Нам нужно привести свои данные к формату обучающего набора данных. Подготовка данных указана в этой статье: `Ross Z.E.  [и др.]. Generalized Seismic Phase Detection with Deep Learning // arXiv.org. 2018. Т. physics.geo-ph.` (раздел 2.2, стр 3) и сводится к следующему:

1. Все волновые формы должны быть 4 сек, 100 Гц (400 отсчётов на канал). У нас есть станции, которые, например, 125Гц, нужно всё привести к 100Гц. Параметр частоты лучше вынести в конфиг. 
2. Используем только 3-х канальные волновые формы, нужно делать проверку на это.
3. Ускорения (акселелограммы) приводим к скоростям (сейсмограммам)
4. Для волновых форм необходимо [сделать детренд](https://docs.obspy.org/packages/autogen/obspy.core.stream.Stream.detrend.html), `type=linear` и этот параметр в конфиг то же (тип опции включено/выключено)
5. Добавить возможность фильтрации high-pass, значение по умолчению в конфиге - **2 Hz**, если будет значение -1, то значит фильтрация выключена.
6. И последнее - это нормализация. Нужно найти максимальное абсолютное знаечение на всех трёх сейсмограммах и нормализировать (просто поделить) все значения этого сэмла (три канала) на максимальное абсолютное значение (т.е. без знака).

Всё это можно сделать средствами obspy. В качестве примера можно рассмотреть вот этот файл: https://github.com/interseismic/generalized-phase-detection/blob/master/gpd_predict.py

**ОТДЕЛЬНО** прошу взять вот это событие: https://eqalert.ru/#/events/QgpAn7OW найти это событие в БД, нарисовать все стрейсы по 4 сек без фильтрации, как есть, потом с детрендом все, потом с фильтрацией все, и потом с нормализацией. Картинки все сюда прошу выложить.

**Comment by Syler1984** [comment]
[Picks.zip](https://github.com/jamm1985/seismo-ml-phase-picker/files/4753124/Picks.zip)

> ОТДЕЛЬНО прошу взять вот это событие: https://eqalert.ru/#/events/QgpAn7OW найти это событие в БД

Взял из станции ARGI, которая не является ближайшей к событию. Ближайшая станция ST005, я не нашел ее в архивах, к сожалению.

**Comment by Syler1984** [comment]
Остальные пукты тикета были закрыты в это PR: 
https://github.com/jamm1985/seismo-ml-phase-picker/pull/8
